export const gestaoStyles = {
  abas: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  aba: {
    padding: '10px 16px',
    borderRadius: 10,
    border: '2px solid #e2e8f0',
    background: '#fff',
    color: '#475569',
    fontWeight: 600,
    cursor: 'pointer',
  },
  abaAtiva: {
    padding: '10px 16px',
    borderRadius: 10,
    border: '2px solid #3b82f6',
    background: '#eff6ff',
    color: '#1d4ed8',
    fontWeight: 700,
    cursor: 'pointer',
  },
  chips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  chip: {
    padding: '6px 12px',
    borderRadius: 999,
    border: '1px solid #cbd5e1',
    background: '#f8fafc',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  chipAtivo: {
    padding: '6px 12px',
    borderRadius: 999,
    border: '1px solid #3b82f6',
    background: '#dbeafe',
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
  },
  badgeStatus: (cor) => ({
    display: 'inline-block',
    borderRadius: 999,
    padding: '4px 10px',
    fontSize: 11,
    fontWeight: 700,
    background: `${cor}22`,
    color: cor,
    border: `1px solid ${cor}55`,
  }),
  tabelaWrap: { marginTop: 14, overflowX: 'auto' },
  linhaAcao: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  accordionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 14px',
    background: '#f8fafc',
    borderRadius: 10,
    border: '1px solid #e2e8f0',
    cursor: 'pointer',
    marginBottom: 8,
  },
  origemCard: {
    marginLeft: 16,
    padding: '10px 12px',
    borderLeft: '3px solid #3b82f6',
    background: '#fff',
    borderRadius: 8,
    marginBottom: 8,
  },
  duasColunas: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(280px, 360px)',
    gap: 18,
    alignItems: 'start',
  },
  painelLateral: {
    position: 'sticky',
    top: 12,
    maxHeight: 'calc(100vh - 24px)',
    overflow: 'auto',
  },
};
