import { useEffect, useMemo, useState } from 'react';
import { carregarAcompanhamentoPrazos } from '../services/trackingPrazosService';

const STATUS = { ATRASADO:['Atrasado','danger'], VENCE_HOJE:['Vence hoje','warning'], PROXIMO:['Próximos 3 dias','info'], EM_TRANSITO:['Em trânsito','neutral'], NO_PRAZO:['Entregue no prazo','success'], ENTREGUE_ATRASO:['Entregue com atraso','danger'], SEM_PREVISAO:['Sem previsão','neutral'] };
const numero = (v, c = 0) => Number(v || 0).toLocaleString('pt-BR', { minimumFractionDigits:c, maximumFractionDigits:c });
function dataBr(v) { if (!v) return '-'; const d = new Date(`${String(v).slice(0,10)}T12:00:00`); return Number.isNaN(d.getTime()) ? '-' : d.toLocaleDateString('pt-BR'); }
function dataHora(v) { const d = new Date(v); return !v || Number.isNaN(d.getTime()) ? '-' : d.toLocaleString('pt-BR'); }
function Badge({ status }) { const [label,tone] = STATUS[status] || [status || '-','neutral']; return <span className={`tracking-prazo-badge ${tone}`}>{label}</span>; }
function riscoTransportadora(row) { if (Number(row.atrasadas)>0 || Number(row.aderencia_pct)<80) return ['Crítico','danger']; if (Number(row.aderencia_pct)<95) return ['Atenção','warning']; return ['Saudável','success']; }

export default function TrackingPrazosPage() {
  const [filtros,setFiltros] = useState({ dias:90, transportadora:'', status:'' });
  const [dados,setDados] = useState({ resumo:{}, transportadoras:[], rotas:[], tendencia:[], qualidade:{}, entregas:[] });
  const [aba,setAba] = useState('visao'); const [carregando,setCarregando] = useState(true); const [erro,setErro] = useState('');
  async function carregar(proximos = filtros) { setCarregando(true); setErro(''); try { setDados(await carregarAcompanhamentoPrazos(proximos)); } catch (e) { setErro(e.message || 'Erro ao consultar prazos.'); } finally { setCarregando(false); } }
  useEffect(() => { carregar(); }, []);
  const r = dados.resumo || {}, q = dados.qualidade || {};
  const aderencia = r.entregues ? Number(r.no_prazo || 0) * 100 / Number(r.entregues) : 0;
  const maxTendencia = Math.max(1, ...dados.tendencia.map(item=>Number(item.total||0)));
  const topCriticas = useMemo(()=>dados.transportadoras.slice(0,6),[dados.transportadoras]);
  function selecionarTransportadora(nome) { if (!nome) return; const proximos={...filtros,transportadora:nome,status:''}; setFiltros(proximos); setAba('visao'); carregar(proximos); }
  function limparTransportadora() { const proximos={...filtros,transportadora:'',status:''}; setFiltros(proximos); carregar(proximos); }
  function exportarFila() { const cols=['status_prazo','pedido','nota_fiscal','transportadora','cidade_destino','uf_destino','previsao_cliente','previsao_transportadora','data_entrega','desvio_dias']; const csv=[cols.join(';'),...dados.entregas.map(row=>cols.map(c=>`"${String(row[c]??'').replaceAll('"','""')}"`).join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:'text/csv'})); a.download=`acompanhamento-entregas-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href); }
  return <div className="page-shell tracking-prazos-page">
    <header className="page-top"><div className="page-header"><div className="amd-mini-brand">AMD Log • Gestão operacional</div><h1>Gestão de entregas e prazos</h1><p>Encontre gargalos, acompanhe riscos e navegue do consolidado até cada entrega e transportadora.</p></div><button className="btn-primary" type="button" onClick={()=>carregar()} disabled={carregando}>{carregando?'Atualizando...':'Atualizar agora'}</button></header>
    {filtros.transportadora&&<div className="tracking-contexto"><div><span>Visão da transportadora</span><strong>{filtros.transportadora}</strong></div><button type="button" onClick={limparTransportadora}>Voltar para todas</button></div>}
    {erro?<div className="sim-alert error">{erro}</div>:null}
    <section className="panel-card tracking-prazos-filtros"><label className="field">Período<select value={filtros.dias} onChange={e=>setFiltros({...filtros,dias:Number(e.target.value)})}><option value={30}>Últimos 30 dias</option><option value={90}>Últimos 90 dias</option><option value={180}>Últimos 180 dias</option><option value={365}>Últimos 12 meses</option></select></label><label className="field">Transportadora<input value={filtros.transportadora} onChange={e=>setFiltros({...filtros,transportadora:e.target.value})} placeholder="Todas as transportadoras" /></label><label className="field">Situação<select value={filtros.status} onChange={e=>setFiltros({...filtros,status:e.target.value})}><option value="">Todas</option><option value="ATRASADO">Atrasadas</option><option value="VENCE_HOJE">Vencem hoje</option><option value="PROXIMO">Próximos 3 dias</option><option value="EM_TRANSITO">Em trânsito</option><option value="NO_PRAZO">Entregues no prazo</option><option value="ENTREGUE_ATRASO">Entregues com atraso</option></select></label><button className="btn-secondary" type="button" onClick={()=>carregar()} disabled={carregando}>Aplicar filtros</button></section>
    <div className="tracking-prazos-kpis"><article><span>Em aberto</span><strong>{numero(r.em_aberto)}</strong><small>entregas ainda sem baixa</small></article><article className="danger"><span>Atrasadas</span><strong>{numero(r.atrasadas)}</strong><small>previsão do cliente vencida</small></article><article className="warning"><span>Próximas do prazo</span><strong>{numero(r.proximas)}</strong><small>hoje e próximos 3 dias</small></article><article className="success"><span>Aderência</span><strong>{numero(aderencia,1)}%</strong><small>{numero(r.no_prazo)} de {numero(r.entregues)} entregues</small></article></div>
    <nav className="tracking-prazos-tabs" aria-label="Análises"><button className={aba==='visao'?'active':''} onClick={()=>setAba('visao')} type="button">Visão geral</button><button className={aba==='transportadoras'?'active':''} onClick={()=>setAba('transportadoras')} type="button">Transportadoras</button><button className={aba==='gargalos'?'active':''} onClick={()=>setAba('gargalos')} type="button">Gargalos de rota</button><button className={aba==='fila'?'active':''} onClick={()=>setAba('fila')} type="button">Fila operacional</button></nav>

    {aba==='visao'&&<div className="tracking-gestao-grid"><section className="panel-card tracking-ranking"><div className="tracking-section-title"><div><strong>Transportadoras que exigem atenção</strong><small>Clique para abrir a visão individual</small></div><button type="button" onClick={()=>setAba('transportadoras')}>Ver todas</button></div>{topCriticas.map(row=>{const [label,tone]=riscoTransportadora(row);return <button type="button" className="tracking-ranking-row" key={row.transportadora} onClick={()=>selecionarTransportadora(row.transportadora)}><span className={`tracking-health ${tone}`}>{label}</span><strong>{row.transportadora}</strong><span>{row.aderencia_pct==null?'-':`${numero(row.aderencia_pct,1)}%`} no prazo</span><b>{numero(row.atrasadas)} atrasadas</b><i>›</i></button>})}{!topCriticas.length&&<p className="empty">Nenhuma transportadora no período.</p>}</section>
      <section className="panel-card"><div className="tracking-section-title"><div><strong>Evolução semanal</strong><small>Volume e aderência das entregas</small></div></div><div className="tracking-trend">{dados.tendencia.map(item=><div className="tracking-trend-item" key={item.semana} title={`${numero(item.total)} registros · ${numero(item.aderencia_pct,1)}% no prazo`}><div className="tracking-trend-bars"><span style={{height:`${Math.max(5,Number(item.total)*100/maxTendencia)}%`}}/><em style={{height:`${Math.max(3,Number(item.no_prazo)*100/maxTendencia)}%`}}/></div><b>{item.aderencia_pct==null?'-':`${numero(item.aderencia_pct)}%`}</b><small>{dataBr(item.semana)}</small></div>)}{!dados.tendencia.length&&<p className="empty">Sem dados para a tendência.</p>}</div><div className="tracking-trend-legend"><span>■ Volume</span><span>■ No prazo</span></div></section>
      <section className="panel-card tracking-quality"><div className="tracking-section-title"><div><strong>Qualidade da base</strong><small>Lacunas que reduzem a confiança da gestão</small></div></div><div><span>Sem previsão do cliente</span><strong>{numero(q.sem_previsao_cliente)}</strong></div><div><span>Sem previsão da transportadora</span><strong>{numero(q.sem_previsao_transportadora)}</strong></div><div><span>Sem transportadora</span><strong>{numero(q.sem_transportadora)}</strong></div><div><span>Sem destino completo</span><strong>{numero(q.sem_destino)}</strong></div></section>
      <section className="panel-card tracking-actions"><div className="tracking-section-title"><div><strong>Plano de ação sugerido</strong><small>Prioridades calculadas sobre o recorte atual</small></div></div><ol><li><b>Tratar {numero(r.atrasadas)} entrega(s) vencida(s)</b><span>Comece pela fila operacional ordenada por maior urgência.</span></li><li><b>Atuar nas rotas de maior reincidência</b><span>Separe problema pontual de padrão operacional.</span></li><li><b>Revisar promessa por transportadora</b><span>Aplique o ajuste somente com amostra histórica suficiente.</span></li></ol></section></div>}

    {aba==='transportadoras'&&<section className="table-card"><div className="tracking-prazos-table-head"><div><strong>Gestão por transportadora</strong><small>Ranking operacional e recomendação de ajuste. Clique no nome para navegar.</small></div><span>{dados.transportadoras.length} transportadora(s)</span></div><div className="tracking-prazos-table-wrap"><table><thead><tr><th>Risco</th><th>Transportadora</th><th>Entregues</th><th>No prazo</th><th>Aderência</th><th>Atraso médio</th><th>Em aberto</th><th>Atrasadas</th><th>Ajuste sugerido</th><th>Diagnóstico</th></tr></thead><tbody>{dados.transportadoras.map(row=>{const a=Number(row.ajuste_sugerido_dias||0),n=Number(row.amostra_ajuste||0),[label,tone]=riscoTransportadora(row);return <tr key={row.transportadora}><td><span className={`tracking-health ${tone}`}>{label}</span></td><td><button className="tracking-link" type="button" onClick={()=>selecionarTransportadora(row.transportadora)}>{row.transportadora}</button></td><td>{numero(row.entregues)}</td><td>{numero(row.no_prazo)}</td><td><strong>{row.aderencia_pct==null?'-':`${numero(row.aderencia_pct,1)}%`}</strong></td><td>{numero(row.atraso_medio_dias,1)} dia(s)</td><td>{numero(row.em_aberto)}</td><td className={Number(row.atrasadas)?'delay':''}>{numero(row.atrasadas)}</td><td><span className={`tracking-ajuste ${a?'raise':'keep'}`}>{n<10?'Amostra insuficiente':a?`+${a} dia(s)`:'Manter prazo'}</span></td><td>{n<10?`Somente ${n} entrega(s) válidas.`:a?`Revisar promessa em ${a} dia(s).`:'Prazo aderente ao histórico.'}</td></tr>})}{!dados.transportadoras.length&&<tr><td colSpan="10" className="empty">Sem histórico no recorte.</td></tr>}</tbody></table></div></section>}

    {aba==='gargalos'&&<section className="table-card"><div className="tracking-prazos-table-head"><div><strong>Gargalos por rota</strong><small>Rotas com pelo menos 3 embarques, priorizadas por atrasos e baixa aderência.</small></div><span>Top {dados.rotas.length}</span></div><div className="tracking-prazos-table-wrap"><table><thead><tr><th>Origem</th><th>Destino</th><th>Volume</th><th>Em aberto</th><th>Atrasadas</th><th>Entregues</th><th>Aderência</th><th>Atraso médio</th><th>Leitura</th></tr></thead><tbody>{dados.rotas.map((row,i)=><tr key={`${row.cidade_origem}-${row.uf_origem}-${row.cidade_destino}-${row.uf_destino}`}><td><b>#{i+1}</b> {row.cidade_origem}/{row.uf_origem}</td><td>{row.cidade_destino}/{row.uf_destino}</td><td>{numero(row.total)}</td><td>{numero(row.em_aberto)}</td><td className={Number(row.atrasadas)?'delay':''}>{numero(row.atrasadas)}</td><td>{numero(row.entregues)}</td><td><strong>{row.aderencia_pct==null?'-':`${numero(row.aderencia_pct,1)}%`}</strong></td><td>{numero(row.atraso_medio_dias,1)} dia(s)</td><td>{Number(row.atrasadas)>=3?'Gargalo recorrente':Number(row.aderencia_pct)<90?'Baixa previsibilidade':'Acompanhar'}</td></tr>)}{!dados.rotas.length&&<tr><td colSpan="9" className="empty">Nenhuma rota com amostra suficiente.</td></tr>}</tbody></table></div></section>}

    {aba==='fila'&&<section className="table-card"><div className="tracking-prazos-table-head"><div><strong>Fila operacional: previsão do cliente × entrega</strong><small>Prioridade automática pelos prazos mais críticos</small></div><div className="tracking-table-actions"><span>Atualizado em {dataHora(dados.geradoEm)}</span><button type="button" onClick={exportarFila} disabled={!dados.entregas.length}>Exportar CSV</button></div></div><div className="tracking-prazos-table-wrap"><table><thead><tr><th>Status</th><th>Pedido / NF</th><th>Transportadora</th><th>Destino</th><th>Previsão cliente</th><th>Previsão transportadora</th><th>Data entrega</th><th>Desvio</th></tr></thead><tbody>{dados.entregas.map(row=><tr key={row.id}><td><Badge status={row.status_prazo}/></td><td><strong>{row.pedido||'-'}</strong><small>NF {row.nota_fiscal||'-'}</small></td><td><button className="tracking-link" type="button" onClick={()=>selecionarTransportadora(row.transportadora)}>{row.transportadora||'-'}</button></td><td>{row.cidade_destino||'-'}/{row.uf_destino||'-'}</td><td>{dataBr(row.previsao_cliente)}</td><td>{dataBr(row.previsao_transportadora)}</td><td>{dataBr(row.data_entrega)}</td><td className={Number(row.desvio_dias)>0?'delay':''}>{row.desvio_dias==null?'-':`${Number(row.desvio_dias)>0?'+':''}${row.desvio_dias} dia(s)`}</td></tr>)}{!dados.entregas.length&&<tr><td colSpan="8" className="empty">Nenhuma entrega encontrada.</td></tr>}</tbody></table></div></section>}
  </div>;
}
