const esc = (v = '') => String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const n = (v) => Number(v || 0).toLocaleString('pt-BR');
const p = (v) => `${Number(v || 0).toFixed(1).replace('.', ',')}%`;
const STATUS = { sem_contrato: 'Sem contrato', em_providencia: 'Em providência', vigente: 'Contrato vigente', vencido: 'Vencido', dispensado: 'Dispensado' };

export function abrirLaudoGestaoContratos({ periodo, linhas = [], pendentes = [], geradoPor = '' }) {
  const carteira = linhas.filter((l) => l.no_pareto);
  const totalCtes = carteira.reduce((s, l) => s + Number(l.ctes || 0), 0);
  const vigentes = carteira.filter((l) => l.status_contrato === 'vigente');
  const ctesVigentes = vigentes.reduce((s, l) => s + Number(l.ctes || 0), 0);
  const cobertura = carteira.at(-1)?.percentual_acumulado || 0;
  const coberturaContratada = totalCtes ? ctesVigentes / totalCtes * 100 : 0;
  const fora = Number(linhas[0]?.ctes_sem_vinculo || 0);
  const rows = carteira.map((l) => `<tr><td>${l.posicao}</td><td><strong>${esc(l.transportadora)}</strong></td><td>${n(l.ctes)}</td><td>${p(totalCtes ? Number(l.ctes) / totalCtes * 100 : 0)}</td><td>${p(l.percentual_acumulado)}</td><td><span class="status ${esc(l.status_contrato)}">${esc(STATUS[l.status_contrato] || l.status_contrato)}</span></td><td>${esc(l.inicio_vigencia || '—')}</td><td>${esc(l.fim_vigencia || '—')}</td><td>${esc(l.movimento || '—')}</td><td>${esc(l.observacoes || '')}</td></tr>`).join('');
  const pendingRows = pendentes.slice(0, 100).map((l) => `<tr><td>${esc(l.nome_cte)}</td><td>${n(l.ctes)}</td><td>${esc((l.canais || []).join(', '))}</td><td>${l.incluir === true ? 'Incluir' : l.incluir === false ? 'Não incluir' : 'A decidir'}</td></tr>`).join('');
  const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Laudo de Gestão de Contratos - ${esc(periodo)}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#eef2f7;color:#172033;font:13px Arial,sans-serif}.print{position:fixed;right:20px;top:18px;border:0;border-radius:8px;background:#244fd8;color:#fff;padding:10px 16px;font-weight:bold;cursor:pointer}.page{max-width:1200px;margin:28px auto;padding:34px;background:#fff;box-shadow:0 8px 30px #1b2e4b22}.kicker{color:#315ee7;font-weight:bold;letter-spacing:.12em;font-size:11px}h1{margin:6px 0 2px;font-size:28px}h2{margin:28px 0 10px;font-size:17px}.muted{color:#68758a}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}.card{border:1px solid #dfe5ee;border-left:4px solid #315ee7;border-radius:10px;padding:14px}.card span{display:block;color:#68758a;font-size:11px}.card strong{display:block;margin:5px 0;font-size:22px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#edf2f8;color:#526078;text-align:left;padding:8px}td{border-bottom:1px solid #e8edf3;padding:8px;vertical-align:top}.status{display:inline-block;border-radius:99px;padding:4px 7px;background:#eef1f6}.status.vigente{background:#e7f8f0;color:#087157}.status.sem_contrato,.status.vencido{background:#fff0f0;color:#a52c2c}.status.em_providencia{background:#fff4dc;color:#955b00}.note{padding:13px;border-left:4px solid #e3a832;background:#fff9eb;color:#694b12}.assinatura{margin-top:32px;padding-top:16px;border-top:1px solid #dfe5ee;color:#68758a}@media print{body{background:#fff}.print{display:none}.page{margin:0;max-width:none;box-shadow:none;padding:10mm}.card{break-inside:avoid}thead{display:table-header-group}tr{break-inside:avoid}}
  </style></head><body><button class="print" onclick="window.print()">Imprimir / Salvar PDF</button><main class="page"><div class="kicker">SUPRIMENTOS · GOVERNANÇA</div><h1>Laudo de Gestão de Contratos</h1><div class="muted">Período analisado: ${esc(periodo)} · Gerado em ${new Date().toLocaleString('pt-BR')}</div><section class="cards"><div class="card"><span>Cobertura da carteira</span><strong>${p(cobertura)}</strong><small>${n(totalCtes)} CT-es</small></div><div class="card"><span>Transportadores na carteira</span><strong>${n(carteira.length)}</strong><small>grupo que alcança 80%</small></div><div class="card"><span>CT-es com contrato vigente</span><strong>${p(coberturaContratada)}</strong><small>${n(ctesVigentes)} CT-es · ${vigentes.length}/${carteira.length} transportadores</small></div><div class="card"><span>CT-es fora do cálculo</span><strong>${n(fora)}</strong><small>${pendentes.length} nomes pendentes</small></div></section><h2>Resumo executivo</h2><p>A carteira contratual foi definida pela ordenação decrescente do volume de CT-es até alcançar pelo menos 80% do universo válido do período. Foram considerados tomadores contendo CPX, ITR, GP ou SPEEDMAX e todos os canais.</p><div class="note">Nomes ainda sem vínculo ou sem decisão não compõem o denominador do Pareto. Recomenda-se tratar essas pendências antes da aprovação definitiva do laudo.</div><h2>Carteira dos 80%</h2><table><thead><tr><th>#</th><th>Transportador</th><th>CT-es</th><th>Participação na carteira</th><th>Acumulado</th><th>Contrato</th><th>Início</th><th>Fim</th><th>Movimento</th><th>Observações</th></tr></thead><tbody>${rows}</tbody></table>${pendentes.length ? `<h2>Pendências de vínculo/decisão</h2><table><thead><tr><th>Nome original no CT-e</th><th>CT-es</th><th>Canais</th><th>Decisão</th></tr></thead><tbody>${pendingRows}</tbody></table>${pendentes.length > 100 ? `<p class="muted">Exibidos os 100 maiores de ${pendentes.length} nomes pendentes.</p>` : ''}` : ''}<div class="assinatura">Responsável pela emissão: ${esc(geradoPor || 'Não informado')}</div></main></body></html>`;
  const janela = window.open('', '_blank', 'width=1280,height=900');
  if (!janela) throw new Error('O navegador bloqueou o laudo. Libere pop-ups e tente novamente.');
  janela.document.open(); janela.document.write(html); janela.document.close();
}
